name: FTP Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Validate files
      run: |
        find . -name '*.php' -print0 | xargs -0 -n1 php -l
        [ -f index.php ] || exit 1

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: ./htdocs/
        exclude: |
          **/.git*
          **/.github*
          **/config/database.php
          **/uploads/*
          **/tests/*
          **/sql/*
          **/README.md
